version: "3"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  backend:
    image: videocall_backend:latest
    env_file:
      - ./envs/prod.env
    command: "sh /scripts/run.sh"
    depends_on:
      - postgres
    volumes:
      - static-files:/static-files
      - media-files:/media-files
      #map static files from backend container to docker volume then send to frontend
      - r-client-web:/r-client-web/build

  server:
    image: videocall:server
    command: "node index.js"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static-files:/static-files
      - media-files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt
      - r-client-web:/r-client-web

# declaration of files we use for volume mapping between containers
volumes:
  postgres_volume:
  static-files:
  media-files:
  r-client-web:
